### ISSUE TITLE
Only i2c_lcd1602_set_backlight works. 

### ISSUE THREAD

**Issue by avidadearthur** [DavidAntliff/esp32-i2c-lcd1602-example#9]
Hello,

I'm currently using an **ESP32-WROOM dev board from AZ-Delivery and a 16x02 LCD display with a PCF8574T I2C driver** and I can't get the display to work. 

Before I found your example, I tried using the [HD44780](https://github.com/maxsydney/ESP32-HD44780) lib and I would get gibberish values that didn't match what the example was sending. Now, with the code you shared **I can only turn the display ON/OFF but the following functions have no effect.**

I have already checked the GPIO (G21 and G22) and the I2C address.  **What do you think I could be doing wrong on my side?**

Thanks for your attention in advance!

**Comment by DavidAntliff** [comment]
Hi, it's near impossible for me to debug this without identical hardware, as I hope you understand.

I would try it with the Arduino LCD display library, as it tends to have the widest compatibility.

Do you have a second device of the same kind that you can use to reduce the possibility of a hardware fault?

If you have a logic analyser, you could use it to verify that the I2C data is not being corrupted, although that doesn't really tell you if the device itself is marginal. A proper scope can help, to check the signals look clean. In my experience, bad I2C can cause all sorts of problems. You could try changing the value of the pull-up resistors too - for example, try 5k instead of 10k, or vice versa, or try a shorter cable or slower I2C clock speed.

Note that my library was really only written for a particular "LCD1602" device I had in my project at the time, and there are a lot of variants. They are meant to all work the same way, but there are subtle differences and without the actual hardware I couldn't really say. I hope you're able to find out why your device is not working.

**Comment by avidadearthur** [comment]
It was a problem with the voltage supply. Thanks for the advice!
